// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yizayhkscxjijxazbxcz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpemF5aGtzY3hqaWp4YXpieGN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0Njg2MDIsImV4cCI6MjA2MjA0NDYwMn0.K32N_F9Rwu6U3FIeLSQZcfxxkLrV1kWa88gPrfCLS8s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);